package config

import (
	"fmt"
	"strings"

	"github.com/confighub/sdk/core/third_party/gaby"
)

// An install is a literal manifest plus a short list of edits to it.
//
// The manifests in manifests/ are real Kubernetes objects, valid and applyable
// as they stand. They are not templates and contain no substitution syntax, so
// they can be read, diffed, linted, validated against a cluster, and scanned by
// policy tooling -- none of which is possible for a document that only becomes a
// manifest after being rendered.
//
// What varies per install is expressed as data rather than as syntax embedded in
// the document: a path and a value. That has three consequences worth the
// change. A path can be checked to exist before it is written, so renaming a
// field in a manifest fails loudly instead of silently producing an object with
// a field missing -- where a mistyped {{ .Nmaespace }} renders empty and ships.
// The set of edits is inspectable, so what an install changes can be printed and
// tested without rendering anything. And an edit is the same shape as a
// ConfigHub mutation, so the configuration this produces can eventually be
// handed to the instance to manage rather than regenerated by rerunning a
// generator.

// edit sets one value at one path in one document.
type edit struct {
	// doc selects which document within a multi-document file, by index. Most
	// files hold one; services and the ingress hold several.
	doc int

	// path is a gaby path into that document, dot-separated, with array indices
	// as segments (spec.ports.0.nodePort).
	path string

	value any

	// insert allows the path not to exist yet. Off by default: an edit whose
	// path is absent is nearly always a manifest and an edit that have drifted
	// apart, and the only way to notice is to refuse.
	insert bool
}

// segment escapes a path segment that contains dots.
//
// gaby splits a path on ".", so a Kubernetes annotation key -- which is a DNS
// name and therefore full of them -- has to say which dots are separators and
// which are part of the name. "~1" is the escape, matching
// yamlkit.EscapeDotsInPathSegment; spelled out here rather than imported so this
// package keeps its dependencies to gaby alone.
func segment(s string) string {
	return strings.ReplaceAll(s, ".", "~1")
}

// apply performs a list of edits against a parsed multi-document file.
func apply(docs gaby.Container, edits []edit) error {
	for _, e := range edits {
		if e.doc >= len(docs) {
			return fmt.Errorf("edit for document %d of a file with %d", e.doc, len(docs))
		}
		doc := docs[e.doc]
		if !e.insert && !doc.ExistsP(e.path) {
			return fmt.Errorf("no path %q in document %d: the manifest and this edit have drifted apart", e.path, e.doc)
		}
		if _, err := doc.SetP(e.value, e.path); err != nil {
			return fmt.Errorf("setting %s: %w", e.path, err)
		}
	}
	return nil
}

// remove deletes paths that do not apply to this install -- a NodePort on a
// service that is staying a ClusterIP, or the placeholder that keeps a generated
// map in block style.
func remove(docs gaby.Container, doc int, paths ...string) error {
	if doc >= len(docs) {
		return fmt.Errorf("delete in document %d of a file with %d", doc, len(docs))
	}
	for _, path := range paths {
		if err := docs[doc].DeleteP(path); err != nil {
			return fmt.Errorf("deleting %s: %w", path, err)
		}
	}
	return nil
}

// fillMap writes a generated set of keys into a map, each with the one-line
// reason it exists.
//
// The map is left empty in the manifest rather than seeded. A map parsed from a
// literal "{}" keeps flow style as keys are added, folding the whole object onto
// one line; one gaby creates itself is block style, which is what a reader
// wants.
//
// The comment is attached through gaby's comment-key mechanism and then injected
// back as real YAML, which is what turns the documentation of a variable into
// something a reader of the applied object can see. Without the inject step the
// marker keys are what get emitted.
func fillMap(doc *gaby.YamlDoc, mapPath string, entries []entry) error {
	for _, e := range entries {
		path := mapPath + "." + e.Key
		if _, err := doc.SetP(e.Value, path); err != nil {
			return fmt.Errorf("setting %s: %w", path, err)
		}
		if e.Doc != "" {
			if err := doc.SetCommentKey(path, "head", e.Doc); err != nil {
				return fmt.Errorf("commenting %s: %w", path, err)
			}
		}
	}
	doc.InjectCommentsFromKeys()
	return nil
}
